#!/bin/sh


#Check if there are missing files or folders
if [ ! -f "generate.input" ]; then
	echo "The following file is missing: generate.input"
	echo "The program has been cancelled."
	exit 1
fi

if [ ! -f "functions.cpp" ]; then
	echo "The following file is missing: functions.cpp"
	echo "The program has been cancelled."
	exit 1
fi

if [ ! -f "libraries.h" ]; then
	echo "The following file is missing: libraries.h"
	echo "The program has been cancelled."
	exit 1
fi

if [ ! -f "headers.h" ]; then
	echo "The following file is missing: headers.h"
	echo "The program has been cancelled."
	exit 1
fi

if [ ! -f "global.h" ]; then
	echo "The following file is missing: global.h"
	echo "The program has been cancelled."
	exit 1
fi

if [ ! -d "data/atom_sites" ]; then
	echo "The following directory is missing: data/atom_sites"
	echo "The program has been cancelled."
	exit 1
fi

if [ ! -d "data/unit_cell" ]; then
	echo "The following directory is missing: data/unit_cell"
	echo "The program has been cancelled."
	exit 1
fi


#Run the script
var=$(sed '3q;d' generate.input)
if [ -d "$var" ]; then
	echo "Output directory already exists. Do you want to overwrite the results? (yes/no)"
	read yn
	if [ "$yn" = "yes" ]; then
    		rm -r $var
    		mkdir $var
    		echo "Compiling the program..."
		g++ functions.cpp
		./a.out
		echo "The program has finished."
		rm a.out
	else
    		echo "The program has been cancelled."
	fi
else
	mkdir $var
	echo "Compiling the program..."
	g++ functions.cpp
	./a.out
	echo "The program has finished."
	rm a.out
fi
